In [19]:
# Eval on same base model, direct strategy, and different input and output types

In [20]:
import pandas as pd
from pathlib import Path

In [21]:
## Project root path
pjpath = ''

# Hacky way of finding the project's root path. Do not rely on this, set your own pjpath!
for p in Path.cwd().parents:
    if p.stem == 'llms4mortality':
        pjpath = p
        break

print(f'> Project path is {pjpath}')

> Project path is /home/daucco/Syncthing/Dev/papers/llms4mortality

In [22]:
# Relevant paths
mimicpath = pjpath / 'data/mimiciv'

In [23]:
# Globals

SEED = 42

# Controls which data to load
samp_size = 5000
balanced_data = True

base_models = [
    'llama3',
    'hf.co/QuantFactory/Llama3-Med42-8B-GGUF:Q8_0',
    'hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0',

    # Extras
    'hf.co/cngchis/Llama3.1-medical-GGUF:Q5_K_M',
    #'hf.co/unsloth/gemma-4-E4B-it-GGUF:Q5_K_M',
    'hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-GGUF:Q5_K_M',
    #'hf.co/DevQuasar/Qwen.Qwen3-VL-8B-Instruct-GGUF:Q5_K_M',
    'hf.co/QuantFactory/ghost-8b-beta-GGUF:Q5_K_M',
    #'hf.co/DevQuasar/Qwen.Qwen3-VL-8B-Thinking-GGUF:Q5_K_M',
]

# Experiment configs to try to evaluate
input_type = ['S', 'R', 'RC']
output_type = ['M', 'PM']
num_ctx = [32] # (X 1024) LLM should behave better allowing bigger context. We cannot test anything above 32k due to GPU constraints
temperatures = [0.1, 0.7, 0.9] #[0.0, 0.1, 0.3, 0.7, 1.0]   # Temperature option for the LLM. The greater, the more creative the answer (def 0.1)

In [24]:
# Load precomputed dataframe. Keeps only hadm_id and delta_days_dod (to find patients that died after n days discharge)
# Transform to boolean (patient died within 30 days after discharge)
df = pd.read_csv(mimicpath / f'mimiciv_4_mortality_S{samp_size}{'_balanced' if balanced_data else ''}.csv.gz')

# Resolves deaths within a month
df['DIES'] = df['delta_days_dod'].apply(lambda x: x > 0 and x <= 30)

In [25]:
df.head()

,hadm_id,note_id,subject_id,charttime,text,gender,dod,anchor_age,anchor_year,admittime,...,insurance,marital_status,race,diagnose_group_description,drg_mortality,diagnose_group_mortality,drg_code,age,delta_days_dod,DIES
0,21891113,19147811-DS-5,19147811,2148-09-22,\nName: ___ Unit No: ___\n ...,F,2149-04-22,68,2148,2148-09-19,...,Other,DIVORCED,WHITE,"DISORDERS OF GALLBLADDER & BILIARY TRACT, DISO...",2,MODERATE,"[284, 445]",68,212,False
1,29643114,15193172-DS-9,15193172,2129-06-28,\nName: ___ Unit No: __...,M,2129-07-17,91,2124,2129-06-25,...,Medicare,WIDOWED,WHITE,"CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS, ACU...",3,HIGH,"[201, 281]",96,19,True
2,26747385,16281465-DS-16,16281465,2144-08-25,\nName: ___ Unit No: ___\n \nAdm...,F,2144-09-06,39,2136,2144-07-13,...,Other,MARRIED,ASIAN,"DIGESTIVE MALIGNANCY, DIGESTIVE MALIGNANCY W MCC",3,HIGH,"[240, 374]",47,12,True
3,23932127,15966914-DS-9,15966914,2155-04-26,\nName: ___ Unit No: ___...,M,NaN,57,2148,2155-04-25,...,Other,MARRIED,WHITE,"PERCUTANEOUS CORONARY INTERVENTION W AMI, PERC...",1,LOW,"[174, 247]",64,-1,False
4,27210508,15484986-DS-28,15484986,2167-11-21,\nName: ___ Unit No: ___\...,M,2167-12-11,72,2167,2167-11-16,...,Other,MARRIED,WHITE,"INTRACRANIAL HEMORRHAGE, INTRACRANIAL HEMORRHA...",3,HIGH,"[44, 64]",72,20,True

In [26]:
# Loads sysprompt definitions to fetch the qualified name of each approach
import json

sysprompt_in_fpath = pjpath / 'ollama/sysprompts/sysprompt_in.json'
sysprompt_out_fpath = pjpath / 'ollama/sysprompts/sysprompt_out.json'

with open(sysprompt_in_fpath, 'r') as ifile:
    sprompt_data_in = json.load(ifile)

with open(sysprompt_out_fpath, 'r') as ifile:
    sprompt_data_out = json.load(ifile)

sprompt_in_names = {i_type: sprompt_data_in[i_type]['name'] if 'name' in sprompt_data_in[i_type].keys() else i_type for i_type in input_type}
sprompt_out_names = {o_type: sprompt_data_out[o_type]['name'] if 'name' in sprompt_data_out[o_type].keys() else o_type for o_type in output_type}

In [27]:
# Load results

from sklearn.metrics import precision_recall_fscore_support as prf
from sklearn.metrics import matthews_corrcoef as mcc

results = []

#llm_exp_id = ['simple', 'cot1nn', 'cot1p1', 'cot1nn_wcourse', 'cot1p1_wcourse']
llm_exp_id = ['simple', 'cot1nn', 'cot1p1']
llm_exp_fpath = pjpath / f'exps/results/llms'

for lleid in llm_exp_id:
    for base_model in base_models:
        bmodel_name = base_model.replace('/', '').replace('.', '').replace(':', '_')
        for i_type in input_type:
            for o_type in output_type:
                for nctx in num_ctx:
                    for temp in temperatures:
                        fname = f'{bmodel_name}_{i_type}_{o_type}_{nctx}k_t{str(temp).replace('.', '')}'
                        fpath = llm_exp_fpath / f'{lleid}/{fname}.csv'

                        # Skips missing results
                        if not Path(fpath).is_file():
                            continue

                        df_res = pd.read_csv(fpath, index_col=0)

                        y_true = df.set_index('hadm_id').loc[df_res.index]['DIES']
                        y_pred = df_res.DIES.apply(lambda x: True if x =='YES' else False)

                        res_uf1 = prf(y_true, y_pred, average='micro')[2]
                        res_Mf1 = prf(y_true, y_pred, average='macro')[2]
                        res_mcc = mcc(y_true, y_pred)
                        
                        res = {
                            'LLM STRAT': lleid,
                            'BASE MODEL': base_model,
                            'INPUT_TYPE': sprompt_in_names[i_type],
                            'OUTPUT_TYPE': sprompt_out_names[o_type],
                            'num_ctx': nctx * 1024,
                            'temp': temp,
                            'uf1': res_uf1,
                            'Mf1': res_Mf1,
                            'mcc': res_mcc
                        }
                        results.append(res)

pd.DataFrame(results)

,LLM STRAT,BASE MODEL,INPUT_TYPE,OUTPUT_TYPE,num_ctx,temp,uf1,Mf1,mcc
0,simple,llama3,Summaries,Mortality,32768,0.1,0.775000,0.746557,0.493160
1,simple,llama3,Summaries,Prognosis + mortality,32768,0.1,0.670000,0.669173,0.452718
2,simple,llama3,Text report,Mortality,32768,0.1,0.790000,0.764336,0.528672
3,simple,llama3,Text report,Prognosis + mortality,32768,0.1,0.660000,0.659694,0.450094
4,simple,llama3,Text report + patient data,Mortality,32768,0.1,0.785000,0.755952,0.512326
5,simple,llama3,Text report + patient data,Prognosis + mortality,32768,0.1,0.685000,0.684361,0.490184
6,simple,hf.co/QuantFactory/Llama3-Med42-8B-GGUF:Q8_0,Summaries,Mortality,32768,0.9,0.775000,0.722488,0.467958
7,simple,hf.co/QuantFactory/Llama3-Med42-8B-GGUF:Q8_0,Summaries,Prognosis + mortality,32768,0.9,0.760417,0.738140,0.479257
8,simple,hf.co/QuantFactory/Llama3-Med42-8B-GGUF:Q8_0,Text report + patient data,Mortality,32768,0.9,0.745000,0.631490,0.393754
9,simple,hf.co/QuantFactory/Llama3-Med42-8B-GGUF:Q8_0,Text report + patient data,Prognosis + mortality,32768,0.9,0.768293,0.755147,0.512516
10,simple,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Summaries,Mortality,32768,0.9,0.765000,0.692720,0.439523
11,simple,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Summaries,Prognosis + mortality,32768,0.9,0.810000,0.773810,0.557956
12,simple,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Text report,Mortality,32768,0.9,0.725000,0.630860,0.325946
13,simple,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Text report,Prognosis + mortality,32768,0.9,0.634021,0.632840,0.352390
14,simple,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Text report + patient data,Mortality,32768,0.9,0.700000,0.605211,0.258586
15,simple,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Text report + patient data,Prognosis + mortality,32768,0.9,0.705584,0.702200,0.472629
16,simple,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Summaries,Mortality,32768,0.9,0.830000,0.806268,0.613349
17,simple,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Summaries,Prognosis + mortality,32768,0.9,0.830000,0.813187,0.628107
18,simple,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Text report,Mortality,32768,0.9,0.740000,0.734015,0.519206
19,simple,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Text report,Prognosis + mortality,32768,0.9,0.755000,0.750452,0.562253
20,simple,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Text report + patient data,Mortality,32768,0.9,0.785000,0.774580,0.571733
21,simple,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Text report + patient data,Prognosis + mortality,32768,0.9,0.755000,0.747260,0.533380
22,cot1nn,llama3,Summaries,Mortality,32768,0.1,0.715000,0.713791,0.536269
23,cot1nn,llama3,Summaries,Prognosis + mortality,32768,0.1,0.742105,0.734084,0.505095
24,cot1nn,hf.co/QuantFactory/Llama3-Med42-8B-GGUF:Q8_0,Summaries,Mortality,32768,0.9,0.805000,0.783520,0.567462
25,cot1nn,hf.co/QuantFactory/Llama3-Med42-8B-GGUF:Q8_0,Summaries,Prognosis + mortality,32768,0.9,0.805031,0.794497,0.592377
26,cot1nn,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Summaries,Mortality,32768,0.9,0.785000,0.764506,0.531203
27,cot1nn,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Summaries,Prognosis + mortality,32768,0.9,0.845745,0.836370,0.684682
28,cot1nn,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Summaries,Mortality,32768,0.9,0.870000,0.851852,0.704570
29,cot1nn,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Summaries,Prognosis + mortality,32768,0.9,0.873684,0.860704,0.722322
30,cot1p1,llama3,Summaries,Mortality,32768,0.1,0.765000,0.692720,0.439523
31,cot1p1,llama3,Summaries,Prognosis + mortality,32768,0.1,0.655738,0.653711,0.392413
32,cot1p1,hf.co/QuantFactory/Llama3-Med42-8B-GGUF:Q8_0,Summaries,Mortality,32768,0.9,0.750000,0.641577,0.408267
33,cot1p1,hf.co/QuantFactory/Llama3-Med42-8B-GGUF:Q8_0,Summaries,Prognosis + mortality,32768,0.9,0.693252,0.689878,0.436103
34,cot1p1,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Summaries,Mortality,32768,0.9,0.740000,0.648601,0.369258
35,cot1p1,hf.co/DevQuasar/google.medgemma-4b-it-GGUF:Q8_0,Summaries,Prognosis + mortality,32768,0.9,0.655738,0.653711,0.392413
36,cot1p1,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Summaries,Mortality,32768,0.9,0.715000,0.698341,0.410620
37,cot1p1,hf.co/DevQuasar/nvidia.Qwen3-Nemotron-8B-BRRM-...,Summaries,Prognosis + mortality,32768,0.9,0.715847,0.706296,0.443342