In [43]:
from pathlib import Path
import pandas as pd
import argparse
import json

In [45]:
# Lists of relevant ICD9 and 10 codes for immunosuppressed patients. Taken from supplementary material of reference study.
ICD9_IMMUNO = []
ICD10_IMMUNO = []

In [46]:
# Loads tables as DataFrames
print('> Loading tables...', end='\r')
df_icu = pd.read_csv(PATH_MIMICIV / 'icustays.csv.gz')
df_patients = pd.read_csv(PATH_MIMICIV / 'patients.csv.gz')
df_icd = pd.read_csv(PATH_MIMICIV / 'diagnoses_icd.csv.gz')
df_dicd = pd.read_csv(PATH_MIMICIV / 'd_icd_diagnoses.csv.gz')

In [47]:
df_icd.head()

   subject_id   hadm_id  seq_num icd_code  icd_version
0    10000032  22595853        1     5723            9
1    10000032  22595853        2    78959            9
2    10000032  22595853        3     5715            9
3    10000032  22595853        4    07070            9
4    10000032  22595853        5      496            9

In [48]:
df_icd.loc[df_icd.icd_code == '1937']

Empty DataFrame
Columns: [subject_id, hadm_id, seq_num, icd_code, icd_version]
Index: []

In [59]:
df_icd9 = df_icd.loc[df_icd.icd_version == 9]
df_icd10 = df_icd.loc[df_icd.icd_version == 10]

In [61]:
set(df_icd.loc[df_icd.icd_code.str.startswith('140')].icd_code.to_list())

{'1400', '1401', '1404', '1409'}

In [50]:
# Load ICD codes as specified in https://link.springer.com/article/10.1186/s40001-025-02622-3
with open(FPATH_JSON_IMMUNO) as f:
    immuno_icds = json.load(f)

    ICD9_IMMUNO = immuno_icds['icd9']
    ICD10_IMMUNO = immuno_icds['icd10']

In [51]:
# Original ICD list contains codes that does not refer to a specific condition,
#   but a category containing such specifications. Since ICD codes are always fully specified in MIMIC-IV
#   (ie, no broad labels are assigned), we need to find the specific subcategories from the original broader specification.
#   We do that by searching for suffixes for each initial code within MIMIC-IV, and keeping all the matches.

# Using sets to ensure unique codes
icd9_full = set()
for x, i in enumerate(ICD9_IMMUNO):
    print(f'> Processing code {i} - ({x+1} out of {len(ICD9_IMMUNO)})' + ' '*50, end='\r')
    icd9_full = icd9_full | set(df_icd.loc[df_icd.icd_code.str.startswith(i)].icd_code.to_list())
    break

icd10_full = set()
for x, i in enumerate(ICD10_IMMUNO):
    print(f'> Processing code {i} - ({x+1} out of {len(ICD10_IMMUNO)})' + ' '*50, end='\r')
    icd10_full = icd10_full | set(df_icd.loc[df_icd.icd_code.str.startswith(i)].icd_code.to_list())
    break
# Export result to disk (same location as the input jsons)

In [52]:
icd9_full

{'1624'}

In [53]:
print(ICD9_IMMUNO)
print()
print(ICD10_IMMUNO)
print(df_icu.columns)
print(df_icd.columns)

['1624', '1984', '1478', '20048', '20402', '1542', '1579', '1578', '1953', '1441', '20037', '20280', '2881', '27949', '1560', '27903', '1533', '20008', '1940', '1961', '20121', '1622', '1992', '20153', '20530', '1573', '1982', '2882', '1760', '1705', '20287', '1974', '1529', '1910', '20412', '28804', '20045', '20211', '1801', '20210', '1929', '1763', '1531', '20050', '20030', '1418', '20047', '20032', '27904', '1832', '20061', '20510', 'V427', '1745', '1461', '1500', '1882', '1887', '1522', '1599', '20058', '19882', '1909', '2880', '1588', '1638', '1888', '1459', '1958', '1943', '1990', '1913', '1700', '1532', '20281', '1631', '20782', '1602', '1600', '1625', '20078', '20020', '1712', '1880', '20005', '20168', '20204', '1908', '27902', '1505', '20080', '1724', '1430', '20591', '20501', '1530', '1821', '1649', '1729', '1706', '20073', '1748', '1479', '1469', '1762', '20010', '1537', '1944', '20273', '1490', '20531', '1515', '1512', '1620', '20051', '20014', '20082', '1890', '1709', '20024', '20060', '20054', '20481', '20150', '2793', '27911', '1919', '20380', '20482', '1609', '1719', '1759', '20018', '20203', '1640', '1841', '19889', '1471', '1419', '1561', '1431', '20035', '1481', '1878', '20581', '20000', '20781', '1716', '27953', '20011', '1451', '1750', '1872', '1898', '1710', '1603', '1980', '1741', '20023', '1889', '20027', '20043', '20161', '1521', '20075', '1514', '20013', '1720', '20052', '20200', '27951', '1722', '1893', '20028', '1769', '1765', '1945', '28802', '1450', '20252', '1921', '1809', '1503', '20033', '1707', '20022', '20278', '20410', '1969', '20411', '28803', '1892', '1534', '1400', '1906', '1511', '1726', '20701', '20288', '20881', '1610', '1598', '1704', '1922', '20076', '1971', '1749', '2799', '20810', '20208', '1972', '1966', '27919', '1828', '1840', '1952', '1510', '1703', '1916', '20302', 'V421', '20286', '20722', '1541', '1881', '2794', '1899', '1628', '1713', '20511', 'V4281', '1834', '1981', '20285', '20290', '1488', '1629', '1727', '1873', '1915', '1570', '1768', '20085', '1516', '1543', '1950', '1409', '1885', '20512', '1725', '1468', '20160', '1568', '20040', '1960', '1764', '1743', '20310', '1571', '1991', '20202', '1643', '20590', '20213', '1519', '1891', '27952', '1963', '1536', '1612', '20041', '1911', '20292', '1611', '20212', '20077', '20880', '1839', '20158', '1483', '28809', '1618', '1552', '1740', '1884', '20021', '1513', '20143', '20301', '20490', '20195', '20296', '1977', '20084', '1968', '1708', '20151', '1508', '1876', '1746', '1550', '1421', '19881', '27901', '20088', '1410', '1518', '20036', '20042', '20191', '1411', '1838', '20108', '27910', '1830', '20600', '1883', '1501', '20291', '20601', '20891', '1877', '1723', '2792', '20400', '1702', '20205', '1717', '20217', '1509', '1520', '1761', '2798', '1869', '1412', '1900', '20220', '20480', '20800', '1923', '1728', '20214', '1744', '20890', '20298', '1844', '20721', '1548', '1429', '20283', '1498', '1440', '20500', 'V420', '20012', '1642', '20293', '1569', '1528', '1630', '1460', '20502', '1973', '1401', '20072', '1404', '20193', '1648', '20221', '20311', '1976', '1718', '79571', '20034', '1608', '20300', '1820', '20610', '1983', '20148', '1975', '1970', '1917', '20070', '20152', '20174', '20064', '1978', '20284', '20295', '1420', '20031', '27906', '1715', '27950', 'V5863', '1572', '20154', '20401', '20206', '1539', '1920', '1874', '1965', '20190', '20275', '20170', '20270', '20120', '1489', '1463', '1574', '20720', '1962', '1912', '27941', '1886', '1540', '1551', '1589', '1808', '1502', '1623', '20198', '20382', '20312', 'V422', '1619', '1986', '1538', '20044', '20192', '042', '20230', '1701', '20260', '20580', '20492', '1639', '1504', '20780', '20702', '1562', '20196', '20197', '20240', '1714', '1453', '1800', '20215', '1742', '1879', '1449', '20201', '1985', '20811', '28800', '20074', '20071', '27900', '1591', '1849', '1914', '1580', '20218', '1535', '20700', '1414', '1458', 'V5869', '1455', '1452', '1918', '1848', '1941', '20282', '1987', '1641', '20194', '1951', '20038', '2386', '20140']

['C040', 'C051', 'C671', 'C7900', 'C7490', 'C8176', 'C91Z0', 'C8193', 'C9302', 'C729', 'C8418', 'C8128', 'C463', 'C50312', 'C7412', 'C8585', 'C7901', 'C8335', 'C84A0', 'Z941', 'C8120', 'C9590', 'C12', 'C8198', 'C499', 'C7492', 'C7651', 'C8313', 'C50812', 'C84A1', 'C8220', 'C9511', 'C548', 'C50411', 'C060', 'C3412', 'C249', 'C543', 'C321', 'C467', 'C8529', 'C9221', 'C8291', 'C761', 'C8334', 'C8388', 'C218', 'C173', 'C8409', 'C966', 'C9621', 'C8233', 'C715', 'C49A1', 'C4911', 'C7401', 'C8108', 'C49A4', 'C50512', 'C8510', 'C020', 'C7931', 'C9240', 'C9480', 'C7919', 'C8350', 'C8178', 'C8590', 'C50219', 'C9160', 'C4370', 'C8589', 'C8289', 'C4001', 'C8103', 'C252', 'C762', 'C711', 'C84A9', 'C4021', 'C8338', 'C8511', 'D831', 'C92Z2', 'C7830', 'C965', 'C8401', 'C130', 'C92Z0', 'C7802', 'C180', 'C3431', 'C9032', 'C7970', 'C7962', 'C160', 'C8331', 'C781', 'C6290', 'C8112', 'C8239', 'C84A8', 'C481', 'C8194', 'C498', 'C229', 'C8191', 'C8373', 'C688', 'C9152', 'C50921', 'C062', 'C4921', 'B20', 'C410', 'C8520', 'C241', 'C311', 'C20', 'C8372', 'C159', 'C069', 'C9010', 'C8138', 'C786', 'C8235', 'C8597', 'C4339', 'C50311', 'C8307', 'C784', 'C8295', 'C52', 'C8140', 'C8100', 'C792', 'C258', 'C8171', 'C8309', 'D700', 'C8283', 'C33', 'C946', 'C439', 'C6291', 'C8379', 'C4081', 'C8280', 'C609', 'C163', 'D804', 'C753', 'C0689', 'C9252', 'C49A3', 'C103', 'C382', 'C153', 'C9200', 'C718', 'C608', 'C960', 'C259', 'C7949', 'C8284', 'C773', 'C269', 'C50122', 'C320', 'C55', 'C470', 'C8214', 'C7972', 'C50121', 'C412', 'C469', 'C461', 'C9290', 'C49A2', 'C473', 'D703', 'C9241', 'C260', 'C438', 'C574', 'C8288', 'C8310', 'C9112', 'C84A4', 'C257', 'C8123', 'C139', 'C300', 'C7889', 'C700', 'C542', 'C4351', 'C9101', 'C8442', 'C8599', 'C768', 'C8240', 'C8370', 'C8376', 'C3482', 'C9230', 'C712', 'C328', 'C8522', 'C3400', 'C50112', 'C111', 'C96A', 'C168', 'C717', 'C482', 'C8208', 'C8219', 'C9421', 'C8594', 'C8356', 'C480', 'C7951', 'C8299', 'C490', 'C49A9', 'Z9481', 'C801', 'C540', 'C187', 'C8172', 'C8449', 'C388', 'C779', 'C677', 'C413', 'C9142', 'C962', 'C8317', 'C4330', 'C50822', 'C578', 'C680', 'C039', 'C9162', 'C600', 'C4371', 'C7491', 'C4022', 'C50412', 'C7982', 'C01', 'C50519', 'C661', 'C9440', 'C186', 'C8308', 'C8371', 'C519', 'C8519', 'C8293', 'C8440', 'C8223', 'C181', 'C169', 'C23', 'C750', 'C162', 'D802', 'C185', 'C048', 'C641', 'C450', 'C8312', 'C8408', 'C8230', 'C7641', 'C9481', 'C210', 'C8353', 'C541', 'C8122', 'C8265', 'C155', 'C8110', 'C9102', 'C9020', 'C4372', 'C539', 'C8199', 'C675', 'C184', 'C493', 'C8209', 'C73', 'C099', 'C9591', 'C8109', 'C4359', 'C8285', 'C164', 'C8300', 'C37', 'C787', 'C4922', 'C8528', 'C91Z2', 'C9191', 'C8382', 'C8319', 'C8129', 'C8359', 'C8330', 'C8234', 'C8281', 'C7932', 'C802', 'C061', 'C549', 'C8587', 'D830', 'C228', 'C701', 'C5702', 'C089', 'C462', 'Z942', 'Z944', 'C301', 'C9212', 'C8311', 'C8499', 'C50211', 'C8514', 'C8512', 'C4322', 'C8374', 'C7910', 'C579', 'C760', 'C9031', 'R75', 'C9030', 'C7880', 'C119', 'C4362', 'C676', 'C772', 'C518', 'C9140', 'C414', 'C562', 'C662', 'C8174', 'C9310', 'C652', 'D848', 'C7989', 'C028', 'C61', 'C9251', 'C8258', 'C9211', 'C722', 'C92Z1', 'C778', 'C496', 'C7961', 'C148', 'C538', 'C8298', 'C221', 'C9220', 'C171', 'C8170', 'C9231', 'C8593', 'C8518', 'C9242', 'C58', 'C8381', 'C9111', 'C9202', 'C8460', 'Z940', 'C689', 'C3430', 'C8598', 'C50011', 'C380', 'C8294', 'C322', 'D821', 'C7902', 'C8179', 'C969', 'C19', 'C7652', 'C6990', 'C531', 'C9151', 'C7960', 'C109', 'C342', 'C189', 'C3492', 'C7259', 'C9000', 'C030', 'C250', 'C577', 'C8200', 'C8339', 'C049', 'C494', 'C569', 'D838', 'C108', 'C530', 'C098', 'C024', 'C8231', 'C7642', 'C460', 'C8286', 'C50422', 'C166', 'C679', 'C8211', 'C8513', 'D819', 'C8419', 'C511', 'C7230', 'C8352', 'D841', 'C3490', 'C023', 'C8192', 'C154', 'C5700', 'Z9482', 'C411', 'C8118', 'C3402', 'C188', 'C7940', 'C165', 'C50811', 'Z7901', 'C8380', 'C5701', 'C101', 'C43112', 'C8173', 'C9130', 'C602', 'C884', 'C9500', 'C8111', 'C8523', 'D839', 'C9110', 'C3432', 'C714', 'C8210', 'Z79899', 'C8582', 'C479', 'C7839', 'C8517', 'C8241', 'C419', 'C561', 'C651', 'C673', 'C031', 'C8591', 'C9250', 'C080', 'C001', 'C674', 'C000', 'C8248', 'C8213', 'C670', 'C4331', 'C158', 'C8410', 'C9420', 'C434', 'C50012', 'C49A0', 'C6211', 'C451', 'C7650', 'C050', 'C8400', 'C318', 'C4650', 'C4352', 'C50612', 'C8337', 'C719', 'C8447', 'C9210', 'C3480', 'C4912', 'C6932', 'C211', 'C253', 'C8448', 'C9001', 'C510', 'C9232', 'C8119', 'C50919', 'C8332', 'C9100', 'C669', 'D849', 'C8592', 'C8389', 'C251', 'C9300', 'C50511', 'C649', 'C310', 'C9301', 'C8443', 'C7971', 'C799', 'C771', 'C138', 'C632', 'C8221', 'C8445', 'C9002', 'C8441', 'C021', 'C720', 'C7800', 'C029', 'C7981', 'C8468', 'C91Z1', 'C774', 'D71', 'C248', 'C3481', 'C179', 'C227', 'C488', 'C710', 'C8588', 'C170', 'C7640', 'C8580', 'C8196', 'C8292', 'C172', 'C8238', 'C383', 'C3401', 'C3491', 'C495', 'D803', 'C601', 'C329', 'C254', 'C8491', 'C8259', 'C8212', 'C9592', 'C182', 'C6212', 'C8583', 'C459', 'D801', 'C50911', 'C50111', 'C50611', 'C642', 'C220', 'C7801', 'C261', 'C785', 'C880', 'C800', 'C9201', 'C004', 'C8358', 'C754', 'C7911', 'C573', 'C8190', 'C92A0', 'C384', 'C457', 'C678', 'C9261', 'C009', 'C240', 'C8444', 'C059', 'C50912', 'C8378', 'C9141', 'C8318', 'C4002', 'C118', 'C8336', 'C8333', 'C161', 'C3411', 'C323', 'C782', 'C6292', 'C8405', 'C8315', 'C090', 'C7952', 'C716', 'C8290', 'C763', 'C672', 'C8515', 'C92A2', 'C775', 'C770', 'C07', 'C052', 'C9150', 'C183', 'C50212', 'C381', 'C140', 'C8581', 'C713']
Index(['subject_id', 'hadm_id', 'stay_id', 'first_careunit', 'last_careunit',
       'intime', 'outtime', 'los'],
      dtype='object')
Index(['subject_id', 'hadm_id', 'seq_num', 'icd_code', 'icd_version'], dtype='object')

In [54]:
df_icu.head()

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10000032,29079034,39553978,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2180-07-23 14:00:00,2180-07-23 23:50:47,0.410266
1,10000980,26913865,39765666,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2189-06-27 08:42:00,2189-06-27 20:38:27,0.497535
2,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032
3,10001217,27703517,34592300,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-12-19 15:42:24,2157-12-20 14:27:41,0.948113
4,10001725,25563031,31205490,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2110-04-11 15:52:22,2110-04-12 23:59:56,1.338588

In [55]:
# Fetch HADM_IDs consistent with immunosuppressed ICDs

# Ensures correct datatype prior to comparison

# Selects relevant entries of immunosuppressed ICD codes
# Treats ICD9 and 10 separately to avoid collisions
df_icd9 = df_icd.loc[df_icd.icd_version == 9]
df_icd10 = df_icd.loc[df_icd.icd_version == 10]

df_hadmid_immuno = pd.concat([
    df_icd9.loc[df_icd9.astype({'icd_code': 'str'}).icd_code.isin(ICD9_IMMUNO)].hadm_id,
    df_icd10.loc[df_icd10.astype({'icd_code': 'str'}).icd_code.isin(ICD10_IMMUNO)].hadm_id
])

# Gets unique IDs
hadmid_immuno = df_hadmid_immuno.unique()

len(hadmid_immuno)

85969

In [56]:
df_icu.size

585448

In [57]:
# Filters by ICU stays
df_icu.loc[df_icu.hadm_id.isin(hadmid_immuno)].stay_id.unique().size

17460